### ISSUE TITLE
Since dependencies for Package Control are now supported, this sounds like a perfect candidate

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/Pywin32#3]
See https://packagecontrol.io/docs/dependencies

(Just discovered this package again by accident.)

**Comment by facelessuser** [comment]
Yeah, its on my radar, just hasn't been high priority for me.  I think I am literally the only person who uses this package in their plugin.

**Comment by FichteFoll** [comment]
Likely, haven't exactly found a use case so far that I needed to pursue using it. I mean, I could have hooked into some tooltip API but since we have that built-in now ...

**Comment by facelessuser** [comment]
I know, I only use it in SubNotify for windows notifications (at least on windows 7), but honestly, I use Growl for windows and tap into that instead for personal use, and I don't even really use it on windows.

**Comment by FichteFoll** [comment]
The dependency has long been created and is already available for Python 3.8 via PC4. See #10.
