### ISSUE TITLE
FILE_ALL_ACCESS is not defined the same as Windows defines it

### ISSUE THREAD

**Issue by sbreidba** [SublimeText/Pywin32#4]
I know that this site isn't the source of Pywin32, but I like Sublime, so I'm duplicating the issue I entered on SourceForge here just in case you ever run into issues with NTFS permissions (ACEs). It's not a particularly easy one to track down.

The current definition of `FILE_ALL_ACCESS` in `ntsecuritycon` is:

```
FILE_ALL_ACCESS = (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 1023)
```

WinNT.h, however, defines it like this:

```
#define FILE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE | 0x1ff)
```

(1023 is 0x3ff, while 0x1ff is 511). 

I can take a guess where the confusion came from; if you add an ACE with FILE_ALL_ACCESS, you often get back FILE_ALL_ACCESS | 0x200. I think this is NTFS enabling SI_NO_ACL_PROTECT, but I haven't confirmed that.  It's possible that original consumers/definers of that value attempted to an equality comparison instead of a bitwise mask and got back unexpected results - it's hard to say.

**Comment by FichteFoll** [comment]
This repo is unmaintained (and furthermore just a mirror of the official pywin32 Python library). See also #10.
