### ISSUE TITLE
AddSourceToRegistry fails if the user has no rights  to write to the Registry

### ISSUE THREAD

**Issue by ChristianSauer** [SublimeText/Pywin32#5]
Hello,
I noticed that the AddSourceToRegistry function fails with an error if the registry key is not writeable (e.g. you have a user with few rights). 
The Python 2.7. NtEventLogHandler uses this function and does not expext such an error - resulting in hard app crashes if we write to this logger.

For my usecase, it was best to extend the NtEventLogHandler so that it just assumes that the key exists (we can create it in our setup). But I was wondering if it would be possible to  extend this function in a way which guards againsst this case?

**Comment by randy3k** [comment]
AFAIK, this package is not working as `pywin32_system32` is missing. 

Try https://github.com/randy3k/sublime-pywin32 instead. It is a package control dependence.
