### ISSUE TITLE
Could not find a version that satisfies the requirement pywin32==223

### ISSUE THREAD

**Issue by rahul6612** [SublimeText/Pywin32#6]
while pushing my project on heroku i am getting this error.
```
 Could not find a version that satisfies the requirement pywin32==223
 No matching distribution found for pywin32==223
```
any idea please tell me.

**Comment by FichteFoll** [comment]
The repo for [pywin32](https://pypi.org/project/pywin32/) is here: https://github.com/mhammond/pywin32

This repo is a modified mirror that can be embedded in Sublime Text's internal Python interpreter.

**Comment by rahul6612** [comment]
ok thnks
