### ISSUE TITLE
not work on win10 ?

### ISSUE THREAD

**Issue by marxangels** [SublimeText/Pywin32#7]
trying the [demo](https://github.com/SublimeText/Pywin32/blob/master/lib/x64/win32comext/shell/demos/servers/copy_hook.py) on windows 10, but nothing happens

**Comment by pykernel** [comment]
Win10 and win11 "Pywin32/lib/x64/win32comext/shell/demos/servers/copy_hook.py" is invalid. 
I don't know why it's not maintained anymore.

**Comment by deathaxe** [comment]
This repository packs a python 3.3 compatible version of pywin32 for use in Sublime Text plugins.

As upstream package has dropped python 3.3 support any further updates are unlikely to happen.
