### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by Adarma** [SublimeText/Pywin32#9]
Trying to install via Package Control fails on Windows 10. It is unable to download the zip file:

Console:
```
Package Control: Error downloading package. HTTP error 403 downloading https://codeload.github.com/SublimeText/Pywin32/zip/st3-1.1.0.
error: Package Control

Unable to download Pywin32. Please view the console for more details.
```

**Comment by FichteFoll** [comment]
I believe the [python-pywin dependency](https://github.com/packagecontrol/pywin32) might be more up to your needs as it's also more recent, albeit not by much.

That said, the download link referenced in the channel cache and also in your console works for me (https://codeload.github.com/SublimeText/Pywin32/zip/st3-1.1.0). Does this occur with any other package as well?

**Comment by Adarma** [comment]
I have been setting up a new laptop. I followed the advice https://packagecontrol.io/docs/syncing to move my packages over. This was the only one that failed. It is a work laptop, so possible that it was blocked by some security settings. The others worked though...

I just copied the package off the old machine to the new one and it is working ok. I should probably try the dependency you mentioned. The plugin using this is probably from before dependencies were a thing.

Thanks,
You can close this if you want.

**Comment by facelessuser** [comment]
It was most definitely before dependencies was a thing. I was the one who originally packaged this up, but found it easier to use `ctypes` directly, removing the need for this package. I offered it up here as I no longer wanted to maintain it. `ctypes` is more work to initially implement, but I honestly only required Pywin32 for a limited amount of things. so replacing the needed calls with `ctypes` relieved me of one more thing to maintain.

**Comment by Adarma** [comment]
I guess it really was blocked for some reason. [python-pywin dependency](https://github.com/packagecontrol/pywin32) also failed:
```
Package Control: Error downloading package. HTTP error 403 downloading https://codeload.github.com/packagecontrol/pywin32/zip/v0.0.220.
error: Package Control

Unable to download python-pywin32. Please view the console for more details.
```

Maybe the others get downloaded as `.sublime-package` and these are `.zip`...

I downloaded the `v0.0.220.zip` of [python-pywin dependency](https://github.com/packagecontrol/pywin32) by other means. Do you happen to know how to manually install it. I extracted it to the `Packages` folder, in a folder called `python-pywin32` with `loader.code` in the root. Restarting Sublime Text still tries to download the dependency though.

**Comment by FichteFoll** [comment]
Yeah, a 403 sounds concerning, especially if the same URL works for me (and should work in general). Can you access these URLs in your browser? Do you use a proxy?

**Comment by Adarma** [comment]
I'm in Germany. Blocked file type by the company it seems. Can't get it in the browser either. Probably should have checked that first, but didn't think to because the other packages worked fine. Its's an issue on my end.
